site_name: Build and Run a Bootable Container Image with Image Mode for RHEL and Podman
  Desktop
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Access Registry: modules/module-01-access-registry.md
  - Module 2 - Lamp Dev Container: modules/module-02-lamp-dev-container.md
  - Module 3 - Bootable Disk Image: modules/module-03-bootable-disk-image.md
plugins:
- techdocs-core
